version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-crypto-stream
    ports:
      - "9092:9092"
    environment:
      # Mode KRaft (Tanpa Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Listeners
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Config Lainnya
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      # Wajib untuk KRaft (Cluster ID random)
      CLUSTER_ID: "MkU3OEVBNTcdwNTJEDM2Qk"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-crypto-stream
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  postgres:
    image: postgres:15
    container_name: crypto-stream-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crypto-stream-user
      POSTGRES_PASSWORD: crypto-stream-pass
      POSTGRES_DB: crypto-stream-sink
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: